---
- hosts: localhost
  become: true
  tasks:
    - name: copy file to tomcat server
      copy:
        src: /var/lib/jenkins/workspace/hello-world/webapp/target/webapp.war
        dest: /opt/tomcat/latest/webapps
